# monitoring/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ServerMetricViewSet, AssetInfoViewSet, WindowsUpdateViewSet # Import your ViewSets

# Create a router instance.
# The DefaultRouter automatically creates URL patterns for your ViewSets,
# including list views (e.g., /metrics/) and detail views (e.g., /metrics/1/).
router = DefaultRouter()

# Register your ViewSets with the router.
# The first argument is the URL prefix (e.g., 'metrics' will result in /api/metrics/),
# the second is the ViewSet class.
router.register(r'metrics', ServerMetricViewSet)
router.register(r'assets', AssetInfoViewSet)
router.register(r'windows-updates', WindowsUpdateViewSet)

# The API URLs are now determined automatically by the router.
# We include all URLs generated by the router in our urlpatterns.
urlpatterns = [
    path('', include(router.urls)), # This includes all URLs generated by the router
]
